baseURL = 'https://notes.awaymessage.club/'
languageCode = 'en-us'
title = 'My not-quite-daily notes'
theme = 'bilberry'
enableEmoji = true
enableRobotsTXT = true

[params]
	avatarEmail = "ulrichp@fastmail.com"
	permanentTopNav = true
	showReadingTime = true
	baseColor = "#1a5276"
	contentFont = "Atkinson"
	headlineFont = "Atkinson"
	articleFooterFont = "Atkinson Mono"
	css_modules = ["sitefonts.css"]
	js_modules = ["https://kit.fontawesome.com/b5a8721916.js"]

	copyrightBy = "stoppableforce"
	creditsText = "Away Message Club"

	utterances = true
	utterancesJsUrl = "https://utteranc.es/client.js"
	utterancesRepository = "stoppableforce/stoppableforce.github.io"
	utterancesIssueTerm = "pathname"
	utterancesLabel = "Comment"
	utterancesTheme = "boxy-light"
	utterancesCrossOrigin = "anonymous"

	showSocialMedia = true
	socialMediaLinks = [
		{ link = "https://awaymessage.club/@stoppableforce", rel = "me", icon = "fa-brands fa-mastodon" },
		{ link = "https://bsky.app/profile/awaymessage.club", rel = "me", icon = "fa-brands fa-bluesky" },
		{ link = "https://stoppableforce.itch.io", rel = "me", icon = "fa-brands fa-itch-io" }
	]

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'

[caches]
  [caches.images]
    dir = ":cacheDir/images"